### ISSUE TITLE
Order chats by the time of last message

### ISSUE THREAD

**Issue by expwez** [hexalang/hexagram#5]
Currently, there are chats being sorted in unclear order. We need to sort them according to the time of the last message in chat. Example:

1. **Group** expwez said something `15:25`
2. **Group** PeyTy said something `10:25`
3. **Private chat** PeyTy said something `16:25`

The list must be displayed in next order:
1. **Private chat** PeyTy said something `16:25`
2. **Group** expwez said something `15:25`
3. **Group** PeyTy said something `10:25`

Also, the pinned chats must be displayed by the order user set.

**Comment by PeyTy** [comment]
cc @expwez test
